// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Announcement *announcement
	AuditLog     *auditLog
	ChatMessage  *chatMessage
	ChatSession  *chatSession
	Claim        *claim
	Feedback     *feedback
	Post         *post
	SystemConfig *systemConfig
	User         *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Announcement = &Q.Announcement
	AuditLog = &Q.AuditLog
	ChatMessage = &Q.ChatMessage
	ChatSession = &Q.ChatSession
	Claim = &Q.Claim
	Feedback = &Q.Feedback
	Post = &Q.Post
	SystemConfig = &Q.SystemConfig
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Announcement: newAnnouncement(db, opts...),
		AuditLog:     newAuditLog(db, opts...),
		ChatMessage:  newChatMessage(db, opts...),
		ChatSession:  newChatSession(db, opts...),
		Claim:        newClaim(db, opts...),
		Feedback:     newFeedback(db, opts...),
		Post:         newPost(db, opts...),
		SystemConfig: newSystemConfig(db, opts...),
		User:         newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Announcement announcement
	AuditLog     auditLog
	ChatMessage  chatMessage
	ChatSession  chatSession
	Claim        claim
	Feedback     feedback
	Post         post
	SystemConfig systemConfig
	User         user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Announcement: q.Announcement.clone(db),
		AuditLog:     q.AuditLog.clone(db),
		ChatMessage:  q.ChatMessage.clone(db),
		ChatSession:  q.ChatSession.clone(db),
		Claim:        q.Claim.clone(db),
		Feedback:     q.Feedback.clone(db),
		Post:         q.Post.clone(db),
		SystemConfig: q.SystemConfig.clone(db),
		User:         q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Announcement: q.Announcement.replaceDB(db),
		AuditLog:     q.AuditLog.replaceDB(db),
		ChatMessage:  q.ChatMessage.replaceDB(db),
		ChatSession:  q.ChatSession.replaceDB(db),
		Claim:        q.Claim.replaceDB(db),
		Feedback:     q.Feedback.replaceDB(db),
		Post:         q.Post.replaceDB(db),
		SystemConfig: q.SystemConfig.replaceDB(db),
		User:         q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Announcement IAnnouncementDo
	AuditLog     IAuditLogDo
	ChatMessage  IChatMessageDo
	ChatSession  IChatSessionDo
	Claim        IClaimDo
	Feedback     IFeedbackDo
	Post         IPostDo
	SystemConfig ISystemConfigDo
	User         IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Announcement: q.Announcement.WithContext(ctx),
		AuditLog:     q.AuditLog.WithContext(ctx),
		ChatMessage:  q.ChatMessage.WithContext(ctx),
		ChatSession:  q.ChatSession.WithContext(ctx),
		Claim:        q.Claim.WithContext(ctx),
		Feedback:     q.Feedback.WithContext(ctx),
		Post:         q.Post.WithContext(ctx),
		SystemConfig: q.SystemConfig.WithContext(ctx),
		User:         q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
