// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameChatMessage = "chat_message"

// ChatMessage 聊天消息表
type ChatMessage struct {
	ID                int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	SessionID         string                `gorm:"column:session_id;not null;comment:会话ID" json:"session_id"`                              // 会话ID
	Role              string                `gorm:"column:role;not null;comment:角色: user, assistant, system" json:"role"`                   // 角色: user, assistant, system
	Content           string                `gorm:"column:content;not null;comment:消息内容" json:"content"`                                    // 消息内容
	Images            string                `gorm:"column:images;comment:图片URL列表(JSON数组)" json:"images"`                                    // 图片URL列表(JSON数组)
	ImageDescriptions string                `gorm:"column:image_descriptions;comment:图片描述列表(JSON数组)" json:"image_descriptions"`             // 图片描述列表(JSON数组)
	CreatedAt         time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	DeletedAt         soft_delete.DeletedAt `gorm:"column:deleted_at;comment:删除时间 (软删除);softDelete:milli" json:"-"`                         // 删除时间 (软删除)
}

// TableName ChatMessage's table name
func (*ChatMessage) TableName() string {
	return TableNameChatMessage
}
