// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameChatSession = "chat_session"

// ChatSession 聊天会话表
type ChatSession struct {
	ID        int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	SessionID string                `gorm:"column:session_id;not null;comment:会话ID" json:"session_id"`                              // 会话ID
	UserID    int64                 `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                    // 用户ID
	Title     string                `gorm:"column:title;not null;comment:会话标题" json:"title"`                                        // 会话标题
	CreatedAt time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time             `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;comment:删除时间 (软删除);softDelete:milli" json:"-"`                         // 删除时间 (软删除)
}

// TableName ChatSession's table name
func (*ChatSession) TableName() string {
	return TableNameChatSession
}
