// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameClaim = "claim"

// Claim 认领申请表
type Claim struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                                    // 自增ID
	PostID      int64                 `gorm:"column:post_id;not null;comment:发布记录ID" json:"post_id"`                                             // 发布记录ID
	ClaimantID  int64                 `gorm:"column:claimant_id;not null;comment:认领者ID" json:"claimant_id"`                                      // 认领者ID
	Description string                `gorm:"column:description;comment:补充说明" json:"description"`                                                // 补充说明
	ProofImages string                `gorm:"column:proof_images;comment:证明图片" json:"proof_images"`                                              // 证明图片
	Status      string                `gorm:"column:status;not null;default:PENDING;comment:状态 PENDING待确认 MATCHED已匹配 REJECTED已拒绝" json:"status"` // 状态 PENDING待确认 MATCHED已匹配 REJECTED已拒绝
	ReviewedBy  int64                 `gorm:"column:reviewed_by;comment:审核人ID" json:"reviewed_by"`                                               // 审核人ID
	ReviewedAt  time.Time             `gorm:"column:reviewed_at;comment:审核时间" json:"reviewed_at"`                                                // 审核时间
	CreatedAt   time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"`            // 创建时间
	UpdatedAt   time.Time             `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"`            // 更新时间
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:删除时间 (软删除);softDelete:milli" json:"-"`                           // 删除时间 (软删除)
}

// TableName Claim's table name
func (*Claim) TableName() string {
	return TableNameClaim
}
