// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemConfig = "system_config"

// SystemConfig 系统配置表
type SystemConfig struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	ConfigKey   string    `gorm:"column:config_key;not null;comment:配置键名" json:"config_key"`                              // 配置键名
	ConfigValue string    `gorm:"column:config_value;not null;comment:配置值(JSON格式)" json:"config_value"`                   // 配置值(JSON格式)
	Description string    `gorm:"column:description;comment:描述" json:"description"`                                       // 描述
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName SystemConfig's table name
func (*SystemConfig) TableName() string {
	return TableNameSystemConfig
}
