CREATE TABLE `post` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `publisher_id` bigint NOT NULL COMMENT '发布者ID',
  `publish_type` varchar(32) NOT NULL COMMENT '发布类型: LOST, FOUND',
  `item_name` varchar(255) NOT NULL COMMENT '物品名称',
  `item_type` varchar(64) NOT NULL COMMENT '物品类型',
  `campus` varchar(64) NOT NULL COMMENT '校区',
  `location` varchar(255) NOT NULL COMMENT '地点',
  `storage_location` varchar(255) NOT NULL COMMENT '存放地点',
  `event_time` timestamp(3) NOT NULL COMMENT '事件时间',
  `features` text NOT NULL COMMENT '物品特征',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人',
  `contact_phone` varchar(32) NOT NULL COMMENT '联系电话',
  `has_reward` boolean NOT NULL DEFAULT FALSE COMMENT '是否有悬赏',
  `reward_description` varchar(255) NOT NULL DEFAULT '' COMMENT '悬赏说明(仅has_reward为true时有效)',
  `images` text COMMENT '图片列表(JSON数组)',
  `summary` text COMMENT 'AI生成的总结文本(用于向量化)',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态: PENDING, APPROVED, SOLVED, CANCELLED, REJECTED, ARCHIVED',
  `cancel_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '取消原因',
  `reject_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '驳回原因',
  `claim_count` int NOT NULL DEFAULT 0 COMMENT '认领人数',
  `archive_method` varchar(255) NOT NULL DEFAULT '' COMMENT '物品处理方式(归档时填写)',
  `processed_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '处理时间',
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` bigint unsigned DEFAULT '0' COMMENT '删除时间 (软删除)',
  PRIMARY KEY (`id`),
  KEY `idx_publisher_id` (`publisher_id`),
  KEY `idx_status` (`status`),
  KEY `idx_publish_type` (`publish_type`),
  KEY `idx_campus` (`campus`),
  KEY `idx_event_time` (`event_time`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='失物招领发布表';
