// Code generated by "gbc codegen". DO NOT EDIT.

//go:build !gbc_generate_exclude

package generate

import (
	"github.com/zjutjh/mygo/kit"
	"github.com/zjutjh/mygo/swagger"

	"app/comm"
)

func init() {
	// api/admin/approve.go:97
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostStatusInvalid,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfApprove", statusCodes)
	}

	// api/admin/post_manage.go:193
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostStatusInvalid,
			comm.CodeAdminPermissionDenied,
			comm.CodeArchiveReasonRequired,
			comm.CodeArchiveNotExpired,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfArchivePost", statusCodes)
	}

	// api/admin/post_manage.go:90
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostStatusInvalid,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfClaimPost", statusCodes)
	}

	// api/admin/delete_post.go:87
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfDeletePost", statusCodes)
	}

	// api/admin/expired_clean.go:67
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfExpiredClean", statusCodes)
	}

	// api/admin/expired_list.go:127
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfExpiredList", statusCodes)
	}

	// api/admin/export.go:113
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfExportData", statusCodes)
	}

	// api/admin/post_list.go:137
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfPostList", statusCodes)
	}

	// api/admin/reject.go:107
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostStatusInvalid,
			comm.CodeAdminPermissionDenied,
			comm.CodeReviewReasonRequired,
			comm.CodeReviewReasonTooLong,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfReject", statusCodes)
	}

	// api/admin/review_detail.go:128
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfReviewDetail", statusCodes)
	}

	// api/admin/review_list.go:138
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfReviewList", statusCodes)
	}

	// api/admin/statistics.go:124
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin.hfStatistics", statusCodes)
	}

	// api/admin/account/create.go:100
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeHashError,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/account.hfCreate", statusCodes)
	}

	// api/admin/account/disable.go:72
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/account.hfDisable", statusCodes)
	}

	// api/admin/account/enable.go:63
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/account.hfEnable", statusCodes)
	}

	// api/admin/account/list.go:118
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/account.hfList", statusCodes)
	}

	// api/admin/account/update.go:85
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeHashError,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/account.hfUpdate", statusCodes)
	}

	// api/admin/system/config.go:84
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/system.hfConfigList", statusCodes)
	}

	// api/admin/system/config.go:280
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/system.hfUpdateClaimValidityDays", statusCodes)
	}

	// api/admin/system/config.go:154
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/system.hfUpdateFeedbackTypes", statusCodes)
	}

	// api/admin/system/config.go:228
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/system.hfUpdateItemTypes", statusCodes)
	}

	// api/admin/system/config.go:332
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/admin/system.hfUpdatePublishLimit", statusCodes)
	}

	// api/agent/history.go:83
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/agent.hfHistory", statusCodes)
	}

	// api/agent/session.go:66
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/agent.hfSession", statusCodes)
	}

	// api/agent/session.go:138
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/agent.hfSessionList", statusCodes)
	}

	// api/agent/stream.go:128
	{
		statusCodes := []kit.Code{
			comm.CodeSessionProcessing,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/agent.hfStream", statusCodes)
	}

	// api/announcement/all_list.go:103
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/announcement.hfAllList", statusCodes)
	}

	// api/announcement/approve.go:77
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostStatusInvalid,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/announcement.hfApprove", statusCodes)
	}

	// api/announcement/delete.go:62
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/announcement.hfDelete", statusCodes)
	}

	// api/announcement/list.go:104
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/announcement.hfList", statusCodes)
	}

	// api/announcement/publish.go:122
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/announcement.hfPublish", statusCodes)
	}

	// api/announcement/review_list.go:102
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/announcement.hfReviewList", statusCodes)
	}

	// api/claim/apply.go:122
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeClaimDuplicate,
			comm.CodeClaimOwnItem,
			comm.CodePostStatusInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/claim.hfApply", statusCodes)
	}

	// api/claim/cancel.go:75
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeClaimNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/claim.hfCancel", statusCodes)
	}

	// api/claim/list_claims.go:109
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/claim.hfList", statusCodes)
	}

	// api/claim/my_list.go:130
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/claim.hfMyList", statusCodes)
	}

	// api/claim/review.go:144
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeClaimAlreadyMatched,
			comm.CodeClaimStatusInvalid,
			comm.CodeClaimNotFound,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/claim.hfReview", statusCodes)
	}

	// api/feedback/detail.go:123
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/feedback.hfDetail", statusCodes)
	}

	// api/feedback/list.go:135
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeAdminPermissionDenied,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/feedback.hfList", statusCodes)
	}

	// api/feedback/my_list.go:120
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/feedback.hfMyList", statusCodes)
	}

	// api/feedback/process.go:87
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/feedback.hfProcess", statusCodes)
	}

	// api/feedback/submit.go:91
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeFeedbackTypeInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/feedback.hfSubmit", statusCodes)
	}

	// api/post/cancel.go:81
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostNotOwner,
			comm.CodePostStatusInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfCancel", statusCodes)
	}

	// api/post/delete.go:80
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostNotOwner,
			comm.CodePostStatusInvalid,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfDelete", statusCodes)
	}

	// api/post/detail.go:150
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfDetail", statusCodes)
	}

	// api/post/my_list.go:125
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfMyList", statusCodes)
	}

	// api/post/publish.go:145
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePublishLimitExceeded,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfPublish", statusCodes)
	}

	// api/post/query.go:128
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfQuery", statusCodes)
	}

	// api/post/update.go:126
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodePostNotOwner,
			comm.CodePostCannotModify,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/post.hfUpdate", statusCodes)
	}

	// api/user/forgot_password.go:80
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeUserNotExist,
			comm.CodeHashError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfForgotPassword", statusCodes)
	}

	// api/user/login.go:95
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeUserNotExist,
			comm.CodePasswordError,
			comm.CodeTokenError,
			comm.CodeUserDisabled,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfLogin", statusCodes)
	}

	// api/user/update.go:85
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
			comm.CodeUserNotExist,
			comm.CodeHashError,
			comm.CodePasswordError,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfUpdate", statusCodes)
	}

	// api/user/upload.go:98
	{
		statusCodes := []kit.Code{
			comm.CodeOK,
		}
		swagger.MustRegisterBusinessStatusCodes("app/api/user.hfUpload", statusCodes)
	}

	// middleware/agent.go:10
	{
		statusCodes := []kit.Code{
			comm.CodeAgentDisabled,
		}
		swagger.MustRegisterBusinessStatusCodes("app/middleware.AgentEnabled.func1", statusCodes)
	}

	// middleware/user_disabled.go:14
	{
		statusCodes := []kit.Code{
			comm.CodeUserDisabled,
		}
		swagger.MustRegisterBusinessStatusCodes("app/middleware.CheckUserDisabled.func1", statusCodes)
	}
}
